version: '3.8'
services:
  php:
    build:
#      context: ./docker/php
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app:/app
      - composer:/root/.composer/cache
    working_dir: /app
    tty: true

volumes:
  composer:

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1200